services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "H%p@yHEreF"
      POSTGRES_DB: "postgres"
    ports:
      - "50000:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: "server@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "passwd"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    restart: unless-stopped
    ports:
      - "5050:80"
    depends_on:
      - postgres
